import Head from 'next/head'
import { Carousel } from '../components/Carousel'
import { Banner } from '../components/Banner'
import { Transport } from '../components/Transport'
import { OrderForm } from '../components/OrderForm'
import { ProductList } from '../components/ProductList'
import { CartList } from '../components/CartList'
import { Header } from '@/layouts/Header'



export default function Home() {



  // JSX
  return (
    <>
      <Head>
        <title>WOWOROOM</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>


      <Header /> {/* 需轉移 */}
      <Banner/>
      <Carousel />
      <Transport />
      <ProductList
        originProduct={products}
        allProducts={allProduct}
      />
      <CartList
        carts={shopCart}
      />

      <OrderForm />
    </>
  )
}
