import Head from 'next/head'
import { Carousel } from '../components/Carousel'
import { Banner } from '../components/Banner'
import { Transport } from '../components/Transport'
import { OrderForm } from '../components/OrderForm'
import { ProductList } from '../components/ProductList'
import { CartList } from '../components/CartList'
import { Header } from '@/layouts/Header'
import { useState } from 'react'


export async function getStaticProps() {
  const productList = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL}/products`
  )
  const cartList = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/carts`)
  const productListData = await productList.json()
  const cartListData = await cartList.json()
  const { products } = await productListData
  const { carts } = await cartListData
  return {
    props: {
      data: { products, carts }
    }
  }
}

export default function Home({ data: { products, carts } }: any) {
  const [shopCart, setShopCart] = useState<any[]>(carts)
  const [allProduct, setAllProduct] = useState<any[]>(products)
  // JSX
  return (
    <>
      <Head>
        <title>WOWOROOM</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Header /> {/* 需轉移 */}
      <Banner />
      <Carousel />
      <Transport />
      <ProductList originProduct={products} allProducts={allProduct} />
      <CartList carts={shopCart} />
      <OrderForm />
    </>
  )
}
